"""Installer: renders one agent file per reachable seat.

Interface
    render(cat, seat) -> str                 the exact file text for a seat
    install(cat, agents_dir) -> Result       writes missing or stale generated files; never touches a foreign file
    check(cat, agents_dir) -> Result         drift: missing, edited, or stale generated files
    uninstall(cat, agents_dir, dry_run) -> Result   removes generated files only

A file is generated when its body carries MARKER. A file without it is foreign and is never written or removed.
Replacing a generated file first copies it to `<name>.md.bak-crews-<UTC ts>`.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from crews import catalog

MARKER = "<!-- claude-crews:generated -->"


@dataclass
class Result:
    written: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    problems: list[str] = field(default_factory=list)
    backups: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, list[str]]:
        return {"written": self.written, "unchanged": self.unchanged, "removed": self.removed,
                "problems": self.problems, "backups": self.backups}


def render(cat: dict[str, Any], seat: dict[str, Any]) -> str:
    kind = cat["kinds"][seat["kind"]]
    effort = seat["effort"]
    level = f" at {effort} effort" if effort else ""
    lines = [
        "---",
        f"name: {seat['agent']}",
        f'description: "claude-crews seat: {seat["kind"]} kind on {seat["model"]}{level}. NEVER dispatch this '
        'agent directly or as a generic reviewer, verifier, or worker: use only the exact Agent call a '
        'mcp__claude-crews__crew_plan result returns, which carries the task specific role, mission, '
        'deliverable, and scope. A dispatch with no matching crew_plan call is blocked."',
        f"tools: {', '.join(seat['tools'])}",
        f"model: {seat['model']}",
    ]
    if effort is not None:
        lines.append(f"effort: {effort}")
    lines += ["---", MARKER, f"<!-- catalog {cat['version']}; edit crews/catalog.json, never this file -->", "",
              kind["body"], ""]
    return "\n".join(lines)


def _is_generated(path: Path) -> bool:
    try:
        return MARKER in path.read_text(encoding="utf-8")
    except (OSError, ValueError):
        return False


def _stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def install(cat: dict[str, Any], agents_dir: Path) -> Result:
    res = Result()
    agents_dir.mkdir(parents=True, exist_ok=True)
    for seat in catalog.reachable_seats(cat):
        target = agents_dir / f"{seat['agent']}.md"
        text = render(cat, seat)
        if target.exists():
            if not _is_generated(target):
                res.problems.append(f"{target.name}: exists and was not generated by claude-crews; left untouched")
                continue
            if target.read_text(encoding="utf-8") == text:
                res.unchanged.append(target.name)
                continue
            backup = target.with_name(f"{target.name}.bak-crews-{_stamp()}")
            shutil.copy2(target, backup)
            res.backups.append(backup.name)
        target.write_text(text, encoding="utf-8")
        res.written.append(target.name)
    return res


def check(cat: dict[str, Any], agents_dir: Path) -> Result:
    res = Result()
    expected = {f"{s['agent']}.md": render(cat, s) for s in catalog.reachable_seats(cat)}
    for name, text in sorted(expected.items()):
        target = agents_dir / name
        if not target.exists():
            res.problems.append(f"{name}: missing")
        elif not _is_generated(target):
            res.problems.append(f"{name}: present but not generated by claude-crews")
        elif target.read_text(encoding="utf-8") != text:
            res.problems.append(f"{name}: drifted from the catalog")
        else:
            res.unchanged.append(name)
    if agents_dir.is_dir():
        for path in sorted(agents_dir.glob("crew-*.md")):
            if path.name not in expected and _is_generated(path):
                res.problems.append(f"{path.name}: generated but no longer in the catalog seat set")
    return res


def uninstall(cat: dict[str, Any], agents_dir: Path, dry_run: bool = False) -> Result:
    res = Result()
    if not agents_dir.is_dir():
        return res
    for path in sorted(agents_dir.glob("*.md")):
        if _is_generated(path):
            if not dry_run:
                path.unlink()
            res.removed.append(path.name)
    return res
