"""Regenerate THIRD_PARTY_NOTICES.md from the installed dist-info of every runtime dependency.

Usage: uv sync && uv run python scripts/gen_notices.py [--check]

The runtime set is the closure of the root package's dependencies in uv.lock (extras followed, dev group
excluded, entries whose marker is only sys_platform == 'win32' skipped because Windows is out of scope). Each
package is read from the project venv: name, version, SPDX id and source URL. The SPDX id comes from the
License-Expression field, else from a License field that is itself an SPDX id, else from the OSI classifier,
else from MANUAL_SPDX, which records a license read by hand from the package's License-File and is verified
here against a phrase of that file. A package whose id cannot be settled is written as UNKNOWN and the script
exits 1.

--check compares the generated text with the file on disk and exits 1 when they differ; it writes nothing.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from importlib import metadata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD_PARTY_NOTICES.md"

CLASSIFIER_SPDX = {
    "License :: OSI Approved :: MIT License": "MIT",
    "License :: OSI Approved :: BSD License": "BSD-3-Clause",
    "License :: OSI Approved :: Apache Software License": "Apache-2.0",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)": "MPL-2.0",
    "License :: OSI Approved :: Python Software Foundation License": "PSF-2.0",
}

KNOWN_SPDX = frozenset({"MIT", "MIT-0", "BSD-2-Clause", "BSD-3-Clause", "Apache-2.0", "MPL-2.0", "PSF-2.0", "ISC"})

# Packages whose metadata names no license expression: id read by hand from the License-File, with a phrase
# that must still appear in that file for the entry to stand.
MANUAL_SPDX: dict[str, tuple[str, str, str]] = {}


def _norm(name: str) -> str:
    return name.lower().replace("_", "-").replace(".", "-")


def runtime_closure(lock: dict, root: str) -> list[str]:
    pkgs = {_norm(p["name"]): p for p in lock["package"]}
    seen: set[str] = set()
    stack = [_norm(root)]
    while stack:
        name = stack.pop()
        if name in seen:
            continue
        seen.add(name)
        pkg = pkgs[name]
        edges = list(pkg.get("dependencies", []))
        for dep in list(edges):
            for extra in dep.get("extra", []):
                edges += pkgs[_norm(dep["name"])].get("optional-dependencies", {}).get(extra, [])
        for dep in edges:
            marker = dep.get("marker", "")
            if marker == "sys_platform == 'win32'":
                continue
            stack.append(_norm(dep["name"]))
    seen.discard(_norm(root))
    return sorted(seen)


def _license_file_text(dist: metadata.Distribution) -> str:
    for f in dist.files or []:
        if "licen" in f.name.lower():
            try:
                return Path(str(dist.locate_file(f))).read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
    return ""


def spdx_for(dist: metadata.Distribution) -> str:
    meta = dist.metadata
    expr = meta.get("License-Expression")
    if expr:
        return str(expr).strip()
    field = str(meta.get("License") or "").strip()
    if field in KNOWN_SPDX:
        return field
    for cls in meta.get_all("Classifier") or []:
        if cls in CLASSIFIER_SPDX:
            return CLASSIFIER_SPDX[cls]
    manual = MANUAL_SPDX.get(_norm(meta["Name"]))
    if manual and manual[1] in _license_file_text(dist):
        return manual[0]
    return "UNKNOWN"


def source_url(dist: metadata.Distribution) -> str:
    meta = dist.metadata
    urls = {}
    for entry in meta.get_all("Project-URL") or []:
        label, _, url = entry.partition(",")
        urls[label.strip().lower()] = url.strip()
    for key in ("source", "source code", "repository", "homepage", "home"):
        if urls.get(key):
            return urls[key]
    if meta.get("Home-page"):
        return str(meta["Home-page"])
    return f"https://pypi.org/project/{meta['Name']}/{meta['Version']}/"


def render() -> tuple[str, int]:
    lock = tomllib.loads((ROOT / "uv.lock").read_text(encoding="utf-8"))
    root = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]["name"]
    rows = []
    unknown = 0
    for name in runtime_closure(lock, root):
        dist = metadata.distribution(name)
        spdx = spdx_for(dist)
        unknown += spdx == "UNKNOWN"
        rows.append((dist.metadata["Name"], dist.version, spdx, source_url(dist)))
    lines = [
        "# Third party notices",
        "",
        "Crews is released under the MIT License (see LICENSE). It depends at run time on the packages below,",
        "each distributed under its own license. This file is generated by `scripts/gen_notices.py` from the",
        "installed dist-info of every runtime dependency in `uv.lock` (development tools are not listed).",
        "A dependency that is only needed on Windows is not listed, because Windows is not supported.",
        "",
        "| Package | Version | License (SPDX) | Source |",
        "|---|---|---|---|",
    ]
    lines += [f"| {n} | {v} | {s} | {u} |" for n, v, s, u in sorted(rows, key=lambda r: r[0].lower())]
    lines += ["", f"Packages listed: {len(rows)}. Packages with an unresolved license: {unknown}.", ""]
    return "\n".join(lines), unknown


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 when THIRD_PARTY_NOTICES.md is stale")
    ns = ap.parse_args()
    text, unknown = render()
    if ns.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("THIRD_PARTY_NOTICES.md is stale; run scripts/gen_notices.py", file=sys.stderr)
            return 1
    else:
        OUT.write_text(text, encoding="utf-8")
    if unknown:
        print(f"{unknown} package(s) with an UNKNOWN license", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
